Load the "MainProcess.xes" file

In [13]:
import os
from pm4py.objects.log.importer.xes import importer as xes_importer
import pandas as pd

# Directory with your .xes files
xes_directory = os.path.join(os.getcwd(), "20130794", "Cleaned Event Log")

# Output directory for models or visuals
output_directory = os.path.join(os.getcwd(), "output")
os.makedirs(output_directory, exist_ok=True)

# Process MainProcess.xes file
filename = "MainProcess.xes"
file_path = os.path.join(xes_directory, filename)
print(f"Processing {filename}")

try:
    log = xes_importer.apply(file_path)
    print("\n\n")
    print(f"Imported {filename} with {len(log)} traces.")
    
    # Print important information about the log
    print(f"Number of events: {sum(len(trace) for trace in log)}")
    activities = set(event["concept:name"] for trace in log for event in trace if "concept:name" in event)
    print(f"Number of unique activities: {len(activities)}")
    print(f"Unique activities: {activities}")
    case_ids = [trace.attributes["concept:name"] for trace in log if "concept:name" in trace.attributes]
    print(f"Number of cases: {len(case_ids)}")
    print(f"First 5 case IDs: {case_ids[:5]}")
    print("\n\n")

except Exception as e:
    print(f"Error processing {filename}: {e}")

Processing MainProcess.xes

parsing log, completed traces :: 100%|██████████| 301/301 [00:00<00:00, 670.24it/s]

Imported MainProcess.xes with 301 traces.
Number of events: 9471
Number of unique activities: 21
Unique activities: {'/dm/lower', '/mm/transport_from_to', '/hbw/store_empty_bucket', '/hbw/unload', '/pm/punch_ribbing', '/sm/sort', '/ov/temper', '/mm/drill', '/vgr/pick_up_and_transport', '/dm/cylindrical_drill', '/hbw/get_empty_bucket', '/hbw/store', '/hw/human_review', '/pm/punch_recesses', '/sm/transport', '/pm/punch_gill', '/dm/drill', '/mm/mill', '/mm/deburr', '/ov/burn', '/wt/pick_up_and_transport'}
Number of cases: 301
First 5 case IDs: ['WF_101_0', 'WF_102_0', 'WF_103_0', 'WF_104_0', 'WF_105_0']

Get all the attributes included in this file ("MainProcess.xes")

In [14]:
try:
    # List all attributes of the traces in a table
    print("\n\nAttributes of traces:\n")
    
    trace_attributes = set()
    for trace in log:
        trace_attributes.update(trace.attributes.keys())
        
    trace_attr_info = []
    for attr in trace_attributes:
        attr_type = "unknown"
        for trace in log:
            if attr in trace.attributes:
                attr_type = type(trace.attributes[attr]).__name__
                break
        trace_attr_info.append({"Attribute": attr, "Type": attr_type})

    trace_attr_df = pd.DataFrame(trace_attr_info)
    display(trace_attr_df)
    # Save the attribute DataFrame to an Excel file in a "tables" subfolder
    tables_dir = os.path.join(os.getcwd(), "tables")
    os.makedirs(tables_dir, exist_ok=True)
    trace_attr_df.to_excel(os.path.join(tables_dir, "main_trace_attribute_info.xlsx"), index=False)
    
    # List all attributes of the events in a table
    print("\n\nAttributes of events:\n")
    
    event_attributes = set()
    for trace in log:
        for event in trace:
            event_attributes.update(event.keys())

    event_attr_info = []
    for attr in event_attributes:
        attr_type = "unknown"
        for trace in log:
            for event in trace:
                if attr in event:
                    attr_type = type(event[attr]).__name__
                    break
            if attr_type != "unknown":
                break
        event_attr_info.append({"Attribute": attr, "Type": attr_type})

    event_attr_df = pd.DataFrame(event_attr_info)
    display(event_attr_df)
    # Save the attribute DataFrame to an Excel file in a "tables" subfolder
    tables_dir = os.path.join(os.getcwd(), "tables")
    os.makedirs(tables_dir, exist_ok=True)
    event_attr_df.to_excel(os.path.join(tables_dir, "main_event_attribute_info.xlsx"), index=False)
except Exception as e:
    print(f"Error processing the log: {e}")

Attributes of traces:

      Attribute Type
0  concept:name  str

Attributes of events:

                                 Attribute      Type
0   human_workstation_green_button_pressed     float
1                             concept:name       str
2                               parameters      dict
3                                 event_id       str
4                     lifecycle:transition       str
5                           time:timestamp  datetime
6                          lifecycle:state       str
7        unsatisfied_condition_description       str
8                        case:concept:name       str
9                         process_model_id       str
10                   requested_service_url       str
11                            org:resource       str
12                      operation_end_time  datetime
13                            current_task       str
14                   complete_service_time       str
15                                    case       str
16                    response_status_code     float
17                            SubProcessID       str
18                                 fier:id       str
19                  planned_operation_time       str
20                           identifier:id       str

List all the resources of the log in a table

In [15]:
try:
    # Set pandas display options for full width
    pd.set_option('display.max_colwidth', None)
    pd.set_option('display.width', 0)
    pd.set_option('display.max_columns', None)

    resources = set()
    for trace in log:
        for event in trace:
            if "org:resource" in event:
                resources.add(event["org:resource"])

    resource_info = []
    for resource in resources:
        # Find the first SubProcessID for this resource by searching events until found
        first_subprocess_id = "N/A"
        parameters_dict = None
        found = False
        for trace in log:
                for event in trace:
                    if event.get("org:resource") == resource:
                        if "SubProcessID" in event:
                            first_subprocess_id = event["SubProcessID"]
                            found = True
                            break
                if found:
                    break
                
        found = False
        for trace in log:
                for event in trace:
                    if event.get("org:resource") == resource:
                        if "parameters" in event:
                            parameters_dict = event["parameters"]
                            found = True
                            break
                if found:
                    break
        event_count = sum(1 for trace in log for event in trace if event.get("org:resource") == resource)
        activities_performed = set(event["concept:name"] for trace in log for event in trace if event.get("org:resource") == resource)
        
        resource_info.append({
            "Resource": resource,
            "Event Count": event_count,
            "Unique Activities": len(activities_performed),
            "Activities": ", ".join(sorted(activities_performed)),
        })

    resource_df = pd.DataFrame(resource_info)
    display(resource_df)
    # Save the attribute DataFrame to an Excel file in a "tables" subfolder
    tables_dir = os.path.join(os.getcwd(), "tables")
    os.makedirs(tables_dir, exist_ok=True)
    resource_df.to_excel(os.path.join(tables_dir, "resources_info.xlsx"), index=False)

except Exception as e:
    print(f"Error processing the log: {e}")

,Resource,Event Count,Unique Activities,Activities
0,wt_1,447,1,/wt/pick_up_and_transport
1,mm_1,576,4,"/mm/deburr, /mm/drill, /mm/mill, /mm/transport_from_to"
2,hw_1,522,1,/hw/human_review
3,ov_2,330,1,/ov/burn
4,wt_2,330,1,/wt/pick_up_and_transport
5,vgr_2,885,1,/vgr/pick_up_and_transport
6,hbw_2,1581,2,"/hbw/store_empty_bucket, /hbw/unload"
7,sm_2,309,2,"/sm/sort, /sm/transport"
8,sm_1,378,2,"/sm/sort, /sm/transport"
9,dm_2,177,3,"/dm/cylindrical_drill, /dm/drill, /dm/lower"
10,ov_1,612,2,"/ov/burn, /ov/temper"
11,pm_1,204,3,"/pm/punch_gill, /pm/punch_recesses, /pm/punch_ribbing"
12,vgr_1,1866,1,/vgr/pick_up_and_transport
13,mm_2,381,4,"/mm/deburr, /mm/drill, /mm/mill, /mm/transport_from_to"
14,hbw_1,873,4,"/hbw/get_empty_bucket, /hbw/store, /hbw/store_empty_bucket, /hbw/unload"

Load a single subevent log file

In [16]:


# Process 0a0a7c16-85d9-48be-a7d5-32931240c337.xes file
filename = "0a0a7c16-85d9-48be-a7d5-32931240c337.xes"
file_path = os.path.join(xes_directory, filename)
print(f"Processing {filename}")

try:
    subevent_log = xes_importer.apply(file_path)
    print("\n\n")
    print(f"Imported {filename} with {len(subevent_log)} traces.")

    # Print important information about the subevent_log
    print(f"Number of events: {sum(len(trace) for trace in subevent_log)}")
    activities = set(event["concept:name"] for trace in subevent_log for event in trace if "concept:name" in event)
    print(f"Number of unique activities: {len(activities)}")
    print(f"Unique activities: {activities}")
    case_ids = [trace.attributes["concept:name"] for trace in subevent_log if "concept:name" in trace.attributes]
    print(f"Number of cases: {len(case_ids)}")
    print(f"First 5 case IDs: {case_ids[:5]}")
    print("\n\n")

except Exception as e:
    print(f"Error processing {filename}: {e}")

Processing 0a0a7c16-85d9-48be-a7d5-32931240c337.xes

parsing log, completed traces :: 100%|██████████| 1/1 [00:00<00:00, 144.08it/s]

Imported 0a0a7c16-85d9-48be-a7d5-32931240c337.xes with 1 traces.
Number of events: 5
Number of unique activities: 5
Unique activities: {'milling the workpiece', 'transporting the workpiece to the sorting machine', 'ejecting the workpiece to the conveyor belt', 'transporting the workpiece to the mill', 'transporting the workpiece to the ejection position'}
Number of cases: 0
First 5 case IDs: []

List all the attributes in this file

In [17]:
try:
    # List all attributes in the subevent_log in a table and display nicely in Jupyter Notebook
    all_attributes = set()
    for trace in subevent_log:
        all_attributes.update(trace.attributes.keys())
        for event in trace:
            all_attributes.update(event.keys())

    # Prepare attribute type information
    attr_info = []
    for attr in all_attributes:
        if attr in subevent_log[0].attributes:
            attr_type = type(subevent_log[0].attributes[attr]).__name__
        elif len(subevent_log[0]) > 0 and attr in subevent_log[0][0]:
            attr_type = type(subevent_log[0][0][attr]).__name__
        else:
            attr_type = "unknown"
        attr_info.append({"Attribute": attr, "Type": attr_type})

    # Display as a pandas DataFrame
    attr_df = pd.DataFrame(attr_info)
    display(attr_df)
    # Save the attribute DataFrame to an Excel file in a "tables" subfolder
    tables_dir = os.path.join(os.getcwd(), "tables")
    os.makedirs(tables_dir, exist_ok=True)
    attr_df.to_excel(os.path.join(tables_dir, "sub_attribute_info.xlsx"), index=False)

except Exception as e:
    print(f"Error processing the subevent_log: {e}")

            Attribute      Type
0      time:timestamp  datetime
1  operation_end_time  datetime
2        concept:name       str
3   stream:datastream      dict
4        SubProcessID       str
5        org:resource       str

Load the database file with the sensor data and query it using DuckDB

In [18]:
import duckdb
import os
from pathlib import Path
import pandas as pd


# Make sure xes_directory is defined before this line
parquet_dir = os.path.join(xes_directory, "parquet")

# Connect to an in-memory DuckDB instance
con = duckdb.connect(database=':memory:')

# Collect all .parquet files in the directory
parquet_file = os.path.join(parquet_dir, "all_combined_new.parquet")

# Ensure there are files to process
if not os.path.exists(parquet_file):
    raise FileNotFoundError(f"No Parquet file found at {parquet_file}")

# Register all Parquet files as a single virtual table
parquet_list_str = f"'{parquet_file}'"
query = f"CREATE VIEW sensor_data AS SELECT * FROM parquet_scan([{parquet_list_str}])"
con.execute(query)

# Print the number of rows in the sensor_data table
if False:
    row_count = con.execute("SELECT COUNT(*) FROM sensor_data").fetchone()[0]
    print(f"Number of rows in sensor_data: {row_count}")

# Print column names
if False:
    info_df = con.execute("PRAGMA table_info('sensor_data')").df()
    print("\nColumns and types in sensor_data:")
    print(info_df['name'])

# Show a sample of the data
if False:
    print("\nSample rows from sensor_data:")
    sample_df = con.execute("SELECT * FROM sensor_data LIMIT 5").df()
    display(sample_df)


# ------------------------
# Enter custom query here
# ------------------------

df_sensor_grouped = con.execute("""
    SELECT 
        *
    FROM sensor_data
    WHERE "org:resource" = 'pm_1'
    AND "concept:name" = 'transporting the workpiece to the punch'
    LIMIT 1
""").df()

# ------------------------


# Display with full width

pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.max_columns', None)
display(df_sensor_grouped)

,trace:SubProcessID,concept:name,org:resource,time:timestamp,operation_end_time,stream:datastream,stream:system,stream:system_type,stream:observation,stream:procedure_type,stream:interaction_type,stream:timestamp,stream:value,sensor_key
0,02d2094a-7ffa-4a52-9c91-5fcd55593308,transporting the workpiece to the punch,pm_1,2021-06-23T15:48:58.201000,2021-06-23T15:49:44.201000,<NA>,http://iot.uni-trier.de/FTOnto#PM_1,sosa:Sensor,http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State,stream:discrete,sosa:Observation,2021-06-23T15:48:58.201000,not ready,stream:point

Number of processes per resource

In [19]:
df_sensor_grouped = con.execute("""
    SELECT 
        "org:resource",
        count(*) AS observation_count,
        SUM(data_points_count) AS total_data_points
        
    FROM 
        (SELECT 
            "org:resource",
            "trace:SubProcessID",
            count(*) AS data_points_count
        FROM sensor_data
        GROUP BY "org:resource", "trace:SubProcessID", 
        )
    GROUP BY "org:resource"
""").df()

# ------------------------


# Display with full width

pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.max_columns', None)
display(df_sensor_grouped)

   org:resource  observation_count  total_data_points
0         vgr_1                575         49035459.0
1          dm_2                 59            81183.0
2         hbw_2                506          1833662.0
3          sm_1                119          6239204.0
4         vgr_2                293           847392.0
5          mm_1                189          7454870.0
6         hbw_1                275         54117983.0
7          hw_1                170           194413.0
8          wt_2                110           235296.0
9          ov_1                197           513777.0
10         ov_2                110           147497.0
11         sm_2                103           115255.0
12         wt_1                147           411339.0
13         mm_2                126            90881.0
14         pm_1                 67           130385.0

Analyse some example process from MainProcess file

In [20]:
# Process MainProcess.xes file
filename = "MainProcess.xes"
file_path = os.path.join(xes_directory, filename)
print(f"Processing {filename}")

try:
    log = xes_importer.apply(file_path)
    print("\n\n")
    print(f"Imported {filename} with {len(log)} traces.")
    
    
    # Display only the concept:name attribute of the events in the first trace
    if len(log) > 0:
        first_trace = log[0]
        print(f"First trace case ID: {first_trace.attributes.get('concept:name', 'N/A')}")
        for idx, event in enumerate(first_trace):
            print(f"Event {idx+1}: concept:name = {event.get('concept:name', 'N/A')}, SubProcessID = {event.get('SubProcessID', 'N/A')}")
    else:
        print("Log is empty, no traces to display.")

    print("\n---\n")
    
    first_subprocess_id = "27958fc0-4484-41ff-9260-e76f8a83a7cd"
    file = first_subprocess_id + ".xes"
    file_path = os.path.join(xes_directory, file)
    
    print(f"Processing subprocess file: {file}")

    sub_log = xes_importer.apply(file_path)
    print(f"Imported {file} with {len(sub_log)} traces.")

    # Display only the concept:name attribute of the events in the first trace of the subprocess log
    if len(sub_log) > 0:
        first_sub_trace = sub_log[0]
        for idx, event in enumerate(first_sub_trace):
            print(f"Event {idx+1}: concept:name = {event.get('concept:name', 'N/A')}, org:resource = {event.get('org:resource', 'N/A')}")
    else:
        print("Subprocess log is empty, no traces to display.")

except Exception as e:
    print(f"Error processing {filename}: {e}")

Processing MainProcess.xes

parsing log, completed traces :: 100%|██████████| 301/301 [00:00<00:00, 680.74it/s]

Imported MainProcess.xes with 301 traces.
First trace case ID: WF_101_0
Event 1: concept:name = /hbw/unload, SubProcessID = N/A
Event 2: concept:name = /hbw/unload, SubProcessID = 27958fc0-4484-41ff-9260-e76f8a83a7cd
Event 3: concept:name = /hbw/unload, SubProcessID = N/A
Event 4: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 5: concept:name = /vgr/pick_up_and_transport, SubProcessID = 4d198444-6633-4218-b1f7-ca67ec666360
Event 6: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 7: concept:name = /hbw/store_empty_bucket, SubProcessID = N/A
Event 8: concept:name = /hbw/store_empty_bucket, SubProcessID = e73aa303-98af-407e-be4e-5ebdee33bc4d
Event 9: concept:name = /hbw/store_empty_bucket, SubProcessID = N/A
Event 10: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 11: concept:name = /vgr/pick_up_and_transport, SubProcessID = 0e7b5a4c-4c03-47b2-96fd-e401ed7fbca9
Event 12: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 13: concept:name = /ov/burn, SubProcessID = N/A
Event 14: concept:name = /ov/burn, SubProcessID = 633d065f-96c0-4c4b-8112-302990575763
Event 15: concept:name = /ov/burn, SubProcessID = N/A
Event 16: concept:name = /ov/temper, SubProcessID = N/A
Event 17: concept:name = /ov/temper, SubProcessID = 27380990-7b3c-4f2e-9475-23b8ca920e73
Event 18: concept:name = /ov/temper, SubProcessID = N/A
Event 19: concept:name = /wt/pick_up_and_transport, SubProcessID = N/A
Event 20: concept:name = /wt/pick_up_and_transport, SubProcessID = 8febb390-19ce-4d63-a018-d9617a8bb1b7
Event 21: concept:name = /wt/pick_up_and_transport, SubProcessID = N/A
Event 22: concept:name = /mm/mill, SubProcessID = N/A
Event 23: concept:name = /mm/mill, SubProcessID = 167db95e-ae8b-4ae8-ac11-055401e11894
Event 24: concept:name = /mm/mill, SubProcessID = N/A
Event 25: concept:name = /mm/deburr, SubProcessID = N/A
Event 26: concept:name = /mm/deburr, SubProcessID = 180236cc-290d-4c7b-ae7c-95ca561e95fe
Event 27: concept:name = /mm/deburr, SubProcessID = N/A
Event 28: concept:name = /sm/sort, SubProcessID = N/A
Event 29: concept:name = /sm/sort, SubProcessID = 16d2bd16-3be9-4daa-a4ad-edb7f5818fcb
Event 30: concept:name = /sm/sort, SubProcessID = N/A
Event 31: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 32: concept:name = /vgr/pick_up_and_transport, SubProcessID = 3166d857-c06e-4881-b71b-42d36bf6a33f
Event 33: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 34: concept:name = /hw/human_review, SubProcessID = N/A
Event 35: concept:name = /hw/human_review, SubProcessID = a8d0fcdd-46c6-44f8-8b19-cecd803d356f
Event 36: concept:name = /hw/human_review, SubProcessID = N/A
Event 37: concept:name = /hbw/get_empty_bucket, SubProcessID = N/A
Event 38: concept:name = /hbw/get_empty_bucket, SubProcessID = b179f074-238d-4666-b50f-9a8959d0a48e
Event 39: concept:name = /hbw/get_empty_bucket, SubProcessID = N/A
Event 40: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 41: concept:name = /vgr/pick_up_and_transport, SubProcessID = 70541c6c-5bd2-4ffe-9bc1-3491f8ab43d0
Event 42: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 43: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 44: concept:name = /vgr/pick_up_and_transport, SubProcessID = 56ddf674-c704-4981-a081-d9173bb459e1
Event 45: concept:name = /vgr/pick_up_and_transport, SubProcessID = N/A
Event 46: concept:name = /hbw/store, SubProcessID = N/A
Event 47: concept:name = /hbw/store, SubProcessID = dc5fef31-159a-4304-ad2d-70de3cd0d63b
Event 48: concept:name = /hbw/store, SubProcessID = N/A

---

Processing subprocess file: 27958fc0-4484-41ff-9260-e76f8a83a7cd.xes

parsing log, completed traces :: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

Imported 27958fc0-4484-41ff-9260-e76f8a83a7cd.xes with 1 traces.
Event 1: concept:name = moving towards the slot 0, org:resource = hbw_2
Event 2: concept:name = picking up the bucket from the slot, org:resource = hbw_2
Event 3: concept:name = transporting the bucket to the conveyor belt, org:resource = hbw_2
Event 4: concept:name = dropping off the bucket at the conveyor belt, org:resource = hbw_2
Event 5: concept:name = transporting the bucket to the vacuum gripper robot crane jib, org:resource = hbw_2

Analyze Subprocess Data

In [21]:
df_sensor_grouped = con.execute("""
    SELECT 
        *
    FROM sensor_data
    WHERE "org:resource" = 'ov_1'
    AND "concept:name" = 'transporting the workpiece to the inside of the oven'
    AND "trace:SubProcessID" = '001618a4-1be3-406c-bd83-ebe5cff5e4f7'
    
""").df()

grouped = df_sensor_grouped.groupby(['stream:system', 'stream:observation'])

for name, group in grouped:
    proc_type = group['stream:procedure_type'].iloc[0]
    print(f"\nGroup: {name}")
    if proc_type == 'stream:continuous':
        # Convert stream:value to numeric if possible
        vals = pd.to_numeric(group['stream:value'], errors='coerce')
        min_val = vals.min()
        max_val = vals.max()
        print(f"  stream:procedure_type = stream:continuous, range: [{min_val}, {max_val}]")
    else:
        unique_vals = group['stream:value'].unique()
        print(f"  stream:procedure_type = {proc_type}, values: {unique_vals}")

Group: ('http://iot.uni-trier.de/FTOnto#OV_1', 'http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature')
  stream:procedure_type = stream:continuous, range: [25.427, 25.427]

Group: ('http://iot.uni-trier.de/FTOnto#OV_1', 'http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State')
  stream:procedure_type = stream:discrete, values: <ArrowStringArray>
['not ready']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#OV_1', 'http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start')
  stream:procedure_type = stream:continuous, range: [3.031237, 5.53083]

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5', 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['1.0', '0.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_Motor_1', 'http://iot.uni-trier.de/FTOnto#MotorSpeed')
  stream:procedure_type = stream:continuous, range: [-512.0, -512.0]

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1', 'http://iot.uni-trier.de/FTOnto#PositionSwitchPressed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2', 'http://iot.uni-trier.de/FTOnto#PositionSwitchPressed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['1.0', '0.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_Valve_7', 'http://iot.uni-trier.de/FTOnto#ValveOpen')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['1.0']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8', 'http://iot.uni-trier.de/FTOnto#CompressorPowerLevel')
  stream:procedure_type = stream:continuous, range: [512.0, 512.0]

Group: ('http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8', 'http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure')
  stream:procedure_type = stream:continuous, range: [0.363, 0.426]

In [22]:
df_sensor_grouped = con.execute("""
    SELECT 
        *
    FROM sensor_data
    WHERE "org:resource" = 'pm_1'
    AND "concept:name" = 'transporting the workpiece to the punch'
    
""").df()

grouped = df_sensor_grouped.groupby(['stream:system', 'stream:observation'])

for name, group in grouped:
    proc_type = group['stream:procedure_type'].iloc[0]
    print(f"\nGroup: {name}")
    if proc_type == 'stream:continuous':
        # Convert stream:value to numeric if possible
        vals = pd.to_numeric(group['stream:value'], errors='coerce')
        min_val = vals.min()
        max_val = vals.max()
        print(f"  stream:procedure_type = stream:continuous, range: [{min_val}, {max_val}]")
    else:
        unique_vals = group['stream:value'].unique()
        print(f"  stream:procedure_type = {proc_type}, values: {unique_vals}")

Group: ('http://iot.uni-trier.de/FTOnto#PM_1', 'http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State')
  stream:procedure_type = stream:discrete, values: <ArrowStringArray>
['not ready']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1', 'http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_Task_Elapsed_Seconds_Since_Start')
  stream:procedure_type = stream:continuous, range: [0.093731, 124.781221]

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_6', 'http://iot.uni-trier.de/FTOnto#Electric_Field_Changed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_7', 'http://iot.uni-trier.de/FTOnto#Electric_Field_Changed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_8', 'http://iot.uni-trier.de/FTOnto#Electric_Field_Changed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['1.0']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_4', 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_5', 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_6', 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['nan']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_7', 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['nan']
Length: 1, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Motor_1', 'http://iot.uni-trier.de/FTOnto#MotorSpeed')
  stream:procedure_type = stream:continuous, range: [-512.0, 512.0]

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Motor_2', 'http://iot.uni-trier.de/FTOnto#MotorSpeed')
  stream:procedure_type = stream:continuous, range: [0.0, 0.0]

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Motor_3', 'http://iot.uni-trier.de/FTOnto#MotorSpeed')
  stream:procedure_type = stream:continuous, range: [0.0, 512.0]

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_1', 'http://iot.uni-trier.de/FTOnto#PositionSwitchPressed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_2', 'http://iot.uni-trier.de/FTOnto#PositionSwitchPressed')
  stream:procedure_type = stream:binary, values: <ArrowStringArray>
['0.0', '1.0']
Length: 2, dtype: str

Group: ('http://iot.uni-trier.de/FTOnto#PM_1_Sink', 'http://iot.uni-trier.de/FTOnto#NFC_Tag_UID')
  stream:procedure_type = stream:discrete, values: <ArrowStringArray>
['6cde5431', '6c565831',      'NaT', '7c0d5831', '0cbc5731', '5c645531',
 '5c865531', 'cc615731', 'ac4f5831', '6cae5731']
Length: 10, dtype: str

Output all the directly follows relations for each resource (used for model creation)

In [23]:
all_resources = ["hbw_1", "hbw_2", "mm_1", "sm_1", "wt_2", "ov_1", "vgr_1", "ov_2", "mm_2", "dm_2", "pm_1", "wt_1", "sm_2", "vgr_2", "hw_1"]

for resource in all_resources:
    df_sensor_grouped = con.execute(f"""
        SELECT 
            "trace:SubProcessID", "time:timestamp", "concept:name"
        FROM sensor_data
        WHERE "org:resource" = '{resource}'
          AND "concept:name" NOT ILIKE 'calibrating%'
        GROUP BY "trace:SubProcessID", "time:timestamp", "concept:name"
    """).df()

    # Group by SubProcessID and collect event names in order
    subprocess_groups = df_sensor_grouped.groupby('trace:SubProcessID')

    events = []

    for sub_id, group in subprocess_groups:
        # Sort by timestamp and get event names
        event_names = group.sort_values('time:timestamp')['concept:name'].tolist()
        # Remove consecutive duplicates
        for i in range(1, len(event_names)):
            if event_names[i] != event_names[i-1] and (event_names[i-1], event_names[i]) not in events:
                events.append((event_names[i-1], event_names[i]))

    # Print all the directly-follows relations
    print(f"\n--- Resource: {resource} ---")
    print(f"Total unique directly-follows relations: {len(events)}")
    num_concept_names = df_sensor_grouped['concept:name'].nunique()
    print(f"Number of unique concept:name values: {num_concept_names}")
    print("Directly-follows relations (event1 -> event2):")
    for e1, e2 in events:
        print(f"  {e1} -> {e2}")

--- Resource: hbw_1 ---
Total unique directly-follows relations: 37
Number of unique concept:name values: 26
Directly-follows relations (event1 -> event2):
  transporting the bucket to the high-bay warehouse crane jib -> transporting the bucket to the high bay warehouse crane jib
  transporting the bucket to the high bay warehouse crane jib -> picking up the bucket from the conveyor belt
  picking up the bucket from the conveyor belt -> dropping off the bucket at the slot
  moving towards the slot 0 -> picking up the bucket from the slot
  picking up the bucket from the slot -> transporting the bucket to the conveyor belt
  transporting the bucket to the conveyor belt -> dropping off the bucket at the conveyor belt
  dropping off the bucket at the conveyor belt -> transporting the bucket to the vacuum gripper robot crane jib
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 0
  transporting the bucket to the slot 0 -> dropping off the bucket at the slot
  moving towards the slot 5 -> picking up the bucket from the slot
  moving towards the slot 3 -> picking up the bucket from the slot
  transporting the bucket to the high bay warehouse crane jib -> transporting the bucket to the slot 1
  transporting the bucket to the slot 1 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 1
  moving towards the slot 2 -> picking up the bucket from the slot
  moving towards the slot 1 -> picking up the bucket from the slot
  transporting the bucket to the high-bay warehouse crane jib -> picking up the bucket from the conveyor belt
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 2
  transporting the bucket to the slot 2 -> dropping off the bucket at the slot
  transporting the bucket to the conveyor belt -> transporting the bucket to the vacuum gripper robot crane jib
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 5
  transporting the bucket to the slot 5 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 7
  transporting the bucket to the slot 7 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 3
  transporting the bucket to the slot 3 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 4
  transporting the bucket to the slot 4 -> dropping off the bucket at the slot
  moving towards the slot 4 -> picking up the bucket from the slot
  moving towards the slot 1 -> transporting the bucket to the conveyor belt
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 6
  transporting the bucket to the slot 6 -> dropping off the bucket at the slot
  moving towards the slot 8 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 8
  transporting the bucket to the slot 8 -> dropping off the bucket at the slot
  moving towards the slot 6 -> picking up the bucket from the slot
  moving towards the slot 7 -> picking up the bucket from the slot

--- Resource: hbw_2 ---
Total unique directly-follows relations: 38
Number of unique concept:name values: 26
Directly-follows relations (event1 -> event2):
  moving towards the slot 6 -> picking up the bucket from the slot
  picking up the bucket from the slot -> transporting the bucket to the conveyor belt
  transporting the bucket to the conveyor belt -> dropping off the bucket at the conveyor belt
  dropping off the bucket at the conveyor belt -> transporting the bucket to the vacuum gripper robot crane jib
  transporting the bucket to the high-bay warehouse crane jib -> transporting the bucket to the high bay warehouse crane jib
  transporting the bucket to the high bay warehouse crane jib -> picking up the bucket from the conveyor belt
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 5
  transporting the bucket to the slot 5 -> dropping off the bucket at the slot
  moving towards the slot 3 -> picking up the bucket from the slot
  moving towards the slot 5 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 1
  transporting the bucket to the slot 1 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 4
  transporting the bucket to the slot 4 -> dropping off the bucket at the slot
  moving towards the slot 7 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 0
  transporting the bucket to the slot 0 -> dropping off the bucket at the slot
  moving towards the slot 2 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 6
  transporting the bucket to the slot 6 -> dropping off the bucket at the slot
  moving towards the slot 4 -> picking up the bucket from the slot
  moving towards the slot 0 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 3
  transporting the bucket to the slot 3 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 7
  transporting the bucket to the slot 7 -> dropping off the bucket at the slot
  moving towards the slot 8 -> picking up the bucket from the slot
  moving towards the slot 1 -> picking up the bucket from the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 8
  transporting the bucket to the slot 8 -> dropping off the bucket at the slot
  picking up the bucket from the conveyor belt -> transporting the bucket to the slot 2
  transporting the bucket to the slot 2 -> dropping off the bucket at the slot
  dropping off the bucket at the slot -> moving towards the slot 6
  picking up the bucket from the conveyor belt -> dropping off the bucket at the slot
  dropping off the bucket at the slot -> moving towards the slot 8
  dropping off the bucket at the slot -> moving towards the slot 4
  dropping off the bucket at the slot -> moving towards the slot 5
  dropping off the bucket at the slot -> moving towards the slot 0

--- Resource: mm_1 ---
Total unique directly-follows relations: 13
Number of unique concept:name values: 8
Directly-follows relations (event1 -> event2):
  transporting the workpiece to the mill -> deburring the workpiece
  deburring the workpiece -> transporting the workpiece to the ejection position
  transporting the workpiece to the ejection position -> ejecting the workpiece to the conveyor belt
  ejecting the workpiece to the conveyor belt -> transporting the workpiece to the sorting machine
  transporting the workpiece to the mill -> milling the workpiece
  milling the workpiece -> transporting the workpiece to the initial position
  transporting the workpiece to the mill -> transporting the workpiece to the ejection position
  milling the workpiece -> transporting the workpiece to the ejection position
  transporting the workpiece to the mill -> drilling the workpiece for 9 seconds
  drilling the workpiece for 9 seconds -> transporting the workpiece to the ejection position
  deburring the workpiece -> ejecting the workpiece to the conveyor belt
  transporting the workpiece to the ejection position -> transporting the workpiece to the sorting machine
  transporting the workpiece to the mill -> transporting the workpiece to the initial position

--- Resource: sm_1 ---
Total unique directly-follows relations: 10
Number of unique concept:name values: 10
Directly-follows relations (event1 -> event2):
  detecting the workpiece color -> transporting the workpiece to the sink 3
  transporting the workpiece to the sink 3 -> ejecting the workpiece to the sink 3
  transporting the workpiece to the light barrier 3 -> transporting the workpiece to the punch or drill
  detecting the workpiece color -> transporting the workpiece to the sink 2
  transporting the workpiece to the sink 2 -> ejecting the workpiece to the sink 2
  detecting the workpiece color -> transporting the workpiece to the sink 1
  transporting the workpiece to the sink 1 -> ejecting the workpiece to the sink 1
  detecting the workpiece color -> ejecting the workpiece to the sink 3
  transporting the workpiece to the light barrier 1 -> detecting the workpiece color
  detecting the workpiece color -> ejecting the workpiece to the sink 2

--- Resource: wt_2 ---
Total unique directly-follows relations: 3
Number of unique concept:name values: 4
Directly-follows relations (event1 -> event2):
  moving towards the oven -> picking up the workpiece from the oven
  picking up the workpiece from the oven -> transporting the workpiece to the milling_machine
  transporting the workpiece to the milling_machine -> dropping off the workpiece at the milling_machine

--- Resource: ov_1 ---
Total unique directly-follows relations: 13
Number of unique concept:name values: 8
Directly-follows relations (event1 -> event2):
  opening the oven door -> transporting the workpiece to the inside of the oven
  transporting the workpiece to the inside of the oven -> temper the workpiece for 40 seconds
  temper the workpiece for 40 seconds -> opening the oven door
  opening the oven door -> transporting the workpiece to the outside of the oven
  transporting the workpiece to the inside of the oven -> burning the workpiece for 10 seconds
  burning the workpiece for 10 seconds -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 15 seconds
  burning the workpiece for 15 seconds -> opening the oven door
  transporting the workpiece to the outside of the oven -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 20 seconds
  burning the workpiece for 20 seconds -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 25 seconds
  burning the workpiece for 25 seconds -> opening the oven door

--- Resource: vgr_1 ---
Total unique directly-follows relations: 32
Number of unique concept:name values: 24
Directly-follows relations (event1 -> event2):
  picking up the workpiece from the high bay warehouse waiting platform -> transporting the workpiece to the high bay warehouse
  transporting the workpiece to the high bay warehouse -> dropping off the workpiece at the high bay warehouse
  picking up the workpiece from the drilling machine sink -> transporting the workpiece to the human workstation
  transporting the workpiece to the human workstation -> dropping off the workpiece at the human workstation
  picking up the workpiece from the drilling machine sink -> transporting the workpiece to the oven
  transporting the workpiece to the oven -> dropping off the workpiece at the oven
  picking up the workpiece from the punching machine sink -> transporting the workpiece to the human workstation
  picking up the workpiece from the human workstation -> transporting the workpiece to the high bay warehouse waiting platform
  transporting the workpiece to the high bay warehouse waiting platform -> dropping off the workpiece at the high bay warehouse waiting platform
  moving towards the drilling machine sink -> picking up the workpiece from the drilling machine sink
  picking up the workpiece from the high bay warehouse -> transporting the workpiece to the oven
  picking up the workpiece from the high bay warehouse waiting platform -> dropping off the workpiece at the high bay warehouse
  moving towards the punching machine sink -> picking up the workpiece from the punching machine sink
  picking up the workpiece from the oven -> transporting the workpiece to the sorting machine conveyor belt
  transporting the workpiece to the sorting machine conveyor belt -> dropping off the workpiece at the sorting machine conveyor belt
  moving towards the sink 2 -> picking up the workpiece from the sink 2
  picking up the workpiece from the sink 2 -> transporting the workpiece to the human workstation
  moving towards the sink 3 -> picking up the workpiece from the sink 3
  picking up the workpiece from the sink 3 -> transporting the workpiece to the human workstation
  dropping off the workpiece at the oven -> moving towards the sink 3
  moving towards the sink 2 -> transporting the workpiece to the human workstation
  moving towards the drilling machine sink -> transporting the workpiece to the oven
  moving towards the sink 1 -> picking up the workpiece from the sink 1
  picking up the workpiece from the sink 1 -> transporting the workpiece to the human workstation
  moving towards the punching machine sink -> transporting the workpiece to the human workstation
  dropping off the workpiece at the high bay warehouse waiting platform -> moving towards the sink 2
  dropping off the workpiece at the human workstation -> moving towards the drilling machine sink
  dropping off the workpiece at the high bay warehouse waiting platform -> moving towards the sink 3
  picking up the workpiece from the human workstation -> dropping off the workpiece at the high bay warehouse waiting platform
  picking up the workpiece from the oven -> dropping off the workpiece at the sorting machine conveyor belt
  dropping off the workpiece at the oven -> picking up the workpiece from the high bay warehouse waiting platform
  dropping off the workpiece at the oven -> moving towards the sink 2

--- Resource: ov_2 ---
Total unique directly-follows relations: 12
Number of unique concept:name values: 8
Directly-follows relations (event1 -> event2):
  opening the oven door -> transporting the workpiece to the inside of the oven
  transporting the workpiece to the inside of the oven -> burning the workpiece for 15 seconds
  burning the workpiece for 15 seconds -> opening the oven door
  opening the oven door -> transporting the workpiece to the outside of the oven
  transporting the workpiece to the inside of the oven -> burning the workpiece for 10 seconds
  burning the workpiece for 10 seconds -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 25 seconds
  burning the workpiece for 25 seconds -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 20 seconds
  burning the workpiece for 20 seconds -> opening the oven door
  transporting the workpiece to the inside of the oven -> burning the workpiece for 30 seconds
  burning the workpiece for 30 seconds -> opening the oven door

--- Resource: mm_2 ---
Total unique directly-follows relations: 19
Number of unique concept:name values: 12
Directly-follows relations (event1 -> event2):
  transporting the workpiece to the mill -> deburring the workpiece
  deburring the workpiece -> transporting the workpiece to the ejection position
  transporting the workpiece to the ejection position -> ejecting the workpiece to the conveyor belt
  ejecting the workpiece to the conveyor belt -> transporting the workpiece to the sorting machine
  transporting the workpiece to the mill -> drilling the workpiece for 3 seconds
  drilling the workpiece for 3 seconds -> transporting the workpiece to the ejection position
  transporting the workpiece to the mill -> milling the workpiece
  milling the workpiece -> transporting the workpiece to the ejection position
  transporting the workpiece to the mill -> drilling the workpiece for 2 seconds
  drilling the workpiece for 2 seconds -> transporting the workpiece to the initial position
  drilling the workpiece for 2 seconds -> transporting the workpiece to the ejection position
  deburring the workpiece -> transporting the workpiece to the initial position
  milling the workpiece -> transporting the workpiece to the initial position
  transporting the workpiece to the mill -> drilling the workpiece for 9 seconds
  drilling the workpiece for 9 seconds -> transporting the workpiece to the ejection position
  transporting the workpiece to the mill -> drilling the workpiece for 4 seconds
  drilling the workpiece for 4 seconds -> transporting the workpiece to the ejection position
  transporting the workpiece to the mill -> drilling the workpiece for 6 seconds
  drilling the workpiece for 6 seconds -> transporting the workpiece to the ejection position

--- Resource: dm_2 ---
Total unique directly-follows relations: 36
Number of unique concept:name values: 20
Directly-follows relations (event1 -> event2):
  transporting the workpiece to the drill -> drilling the workpiece for 10 seconds
  drilling the workpiece for 10 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> lowering the workpiece
  lowering the workpiece -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 8 seconds
  drilling the workpiece for 8 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 12 seconds
  drilling the workpiece for 12 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 28 seconds
  drilling the workpiece for 28 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 15 seconds
  drilling the workpiece for 15 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 24 seconds
  drilling the workpiece for 24 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 14 seconds
  drilling the workpiece for 14 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 20 seconds
  drilling the workpiece for 20 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 9 seconds
  drilling the workpiece for 9 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 21 seconds
  drilling the workpiece for 21 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 35 seconds
  drilling the workpiece for 35 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 30 seconds
  drilling the workpiece for 30 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 18 seconds
  drilling the workpiece for 18 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 4 seconds
  drilling the workpiece for 4 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 5 seconds
  drilling the workpiece for 5 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 3 seconds
  drilling the workpiece for 3 seconds -> transporting the workpiece to the dm_2_sink
  transporting the workpiece to the drill -> drilling the workpiece for 16 seconds
  drilling the workpiece for 16 seconds -> transporting the workpiece to the dm_2_sink

--- Resource: pm_1 ---
Total unique directly-follows relations: 2
Number of unique concept:name values: 3
Directly-follows relations (event1 -> event2):

Find als sensors with discrete values

In [24]:
df_synthetic_data = con.execute("""
    SELECT 
        "stream:observation",
        COUNT(*) AS value_count
    FROM sensor_data
    WHERE "stream:procedure_type" = 'stream:discrete'
    GROUP BY "stream:observation", "stream:procedure_type"
    ORDER BY value_count
""").df()

display(df_synthetic_data)

,stream:observation,value_count
0,http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State,5768
1,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State,8192
2,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State,8211
3,http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State,9291
4,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_State,10180
5,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_State,10704
6,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State,18246
7,NaN,18372
8,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_State,29412
9,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State,34509
10,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State,35158
11,http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State,38730
12,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_State,51707
13,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_State,52962
14,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_State,85351
15,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_State,97384
16,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,108734

Check the amount of nan values per resource

In [25]:
df_synthetic_data = con.execute("""
    SELECT 
        "org:resource",
        "stream:value",
        "stream:observation",
        "stream:system",
        COUNT(*) AS value_count
    FROM sensor_data
    WHERE "stream:value" IS NULL
       OR lower(trim("stream:value")) IN ('none', 'nan', 'null', '')
    GROUP BY "org:resource", "stream:value", "stream:observation", "stream:system"
    ORDER BY value_count
""").df()

# Here it is shown that the number of missing values is equal to the number of all values (all values are missing for these observations)
df = con.execute("""
    SELECT 
        "org:resource",
        "stream:observation",
        "stream:system",
        COUNT(*) AS value_count
    FROM sensor_data
    WHERE "stream:observation" = 'http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted'
        AND "org:resource" IN ('pm_1', 'dm_2')
    GROUP BY "org:resource", "stream:observation", "stream:system"
    ORDER BY value_count
""").df()

display(df_synthetic_data)
display(df)

,org:resource,stream:value,stream:observation,stream:system,value_count
0,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_1,222
1,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_2,719
2,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_3,919
3,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Waiting_Platform,1018
4,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_4,1027
5,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_5,1134
6,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_6,1201
7,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_7,1243
8,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_8,1280
9,hbw_1,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_9,1291
10,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_9,1935
11,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_8,2649
12,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_7,2789
13,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_6,3276
14,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_5,3314
15,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_3,3453
16,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_4,3842
17,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_2,4734
18,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_1,4888
19,dm_2,nan,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_6,5768
20,dm_2,nan,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_7,5768
21,sm_2,NaN,NaN,http://iot.uni-trier.de/FTOnto#SM_2,7258
22,hbw_2,None,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,http://iot.uni-trier.de/FTOnto#HBW_2_Waiting_Platform,7457
23,sm_1,NaN,NaN,http://iot.uni-trier.de/FTOnto#SM_1,9005
24,pm_1,nan,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_7,9291
25,pm_1,nan,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_6,9291

,org:resource,stream:observation,stream:system,value_count
0,dm_2,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_5,5768
1,dm_2,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_6,5768
2,dm_2,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_7,5768
3,dm_2,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_4,5768
4,pm_1,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_6,9291
5,pm_1,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_4,9291
6,pm_1,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_7,9291
7,pm_1,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_5,9291

Find synchronized sensors for a resource

In [ ]:
results = []

for resource in all_resources:
    df = con.execute(f"""
        SELECT 
            "stream:timestamp",
            STRING_AGG(
                DISTINCT "stream:system" || ':' || "stream:observation",
                ', ' ORDER BY "stream:system" || ':' || "stream:observation"
            ) AS sensor_group,
            COUNT(DISTINCT "stream:system" || ':' || "stream:observation") AS num_sensors,
            COUNT(*) AS occurrence_count
        FROM (
            SELECT *
            FROM sensor_data
            WHERE "org:resource" = '{resource}'
            LIMIT 20000
        )
        GROUP BY "stream:timestamp"
        ORDER BY occurrence_count DESC
    """).df()

    if not df.empty:
        df_grouped = df.groupby('sensor_group').agg(
            timestamp_count=('stream:timestamp', 'count'),
            total_occurrences=('occurrence_count', 'sum'),
            num_sensors=('num_sensors', 'first')
        ).reset_index().sort_values('timestamp_count', ascending=False)
        
        print(f"\n--- Resource: {resource} ---")
        display(df_grouped)
        
        # Second table: time intervals analysis
        df_intervals = con.execute(f"""
            SELECT 
            "stream:system" || ':' || "stream:observation" AS sensor,
            COUNT(*) AS total_readings,
            AVG(EXTRACT(EPOCH FROM (timestamp_lead - timestamp_value))) AS avg_interval_seconds,
            STDDEV_POP(EXTRACT(EPOCH FROM (timestamp_lead - timestamp_value))) AS stddev_interval_seconds,
            MIN(EXTRACT(EPOCH FROM (timestamp_lead - timestamp_value))) AS min_interval_seconds,
            MAX(EXTRACT(EPOCH FROM (timestamp_lead - timestamp_value))) AS max_interval_seconds
            FROM (
            SELECT 
                "stream:system",
                "stream:observation",
                "time:timestamp",
                CAST("stream:timestamp" AS TIMESTAMP) AS timestamp_value,
                LEAD(CAST("stream:timestamp" AS TIMESTAMP)) OVER (
                PARTITION BY "stream:system", "stream:observation", "time:timestamp"
                ORDER BY CAST("stream:timestamp" AS TIMESTAMP)
                ) AS timestamp_lead
            FROM sensor_data
            WHERE "org:resource" = '{resource}'
              AND "stream:timestamp" IS NOT NULL
            )
            WHERE timestamp_lead IS NOT NULL
            GROUP BY "stream:system", "stream:observation"
            ORDER BY avg_interval_seconds DESC
        """).df()
        
        print(f"\nTime Intervals Analysis for {resource}:")
        display(df_intervals)

--- Resource: hbw_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
0,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,10220,10220,1
3,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation,4800,4800,1
4,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Magnetic_Field_Strength,4466,4466,1
5,"http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_X, http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_2:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_1_Motor_4:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_5:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_6:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_7:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_8:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",27,486,18
2,"http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration, http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Magnetic_Field_Strength",7,14,2
1,"http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration, http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation",2,4,2
6,"http://iot.uni-trier.de/FTOnto#HBW_1_Slot_1:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_2:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_3:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_4:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_5:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_6:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_7:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_8:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Slot_9:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_1_Waiting_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID",1,10,10

Time Intervals Analysis for hbw_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_5:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
1,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_7:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
2,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_1:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
3,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_6:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
4,http://iot.uni-trier.de/FTOnto#HBW_1_Waiting_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
5,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_3:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
6,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_4:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
7,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_8:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
8,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_2:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
9,http://iot.uni-trier.de/FTOnto#HBW_1_Slot_9:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2187,9839.688877,430292.921481,0.046,2.011786e+07
10,http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,51706,416.187794,88517.020885,0.000,2.011786e+07
11,http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_5:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,51706,416.187794,88517.020885,0.000,2.011786e+07
12,http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,51706,416.187794,88517.020885,0.000,2.011786e+07
13,http://iot.uni-trier.de/FTOnto#HBW_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,51706,416.187794,88517.020885,0.000,2.011786e+07
14,http://iot.uni-trier.de/FTOnto#HBW_1_Motor_4:http://iot.uni-trier.de/FTOnto#MotorSpeed,51706,416.187794,88517.020885,0.000,2.011786e+07
15,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_State,51706,416.187794,88517.020885,0.000,2.011786e+07
16,http://iot.uni-trier.de/FTOnto#HBW_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,51706,416.187794,88517.020885,0.000,2.011786e+07
17,http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_6:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,51706,416.187794,88517.020885,0.000,2.011786e+07
18,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_Y,51706,416.187794,88517.020885,0.000,2.011786e+07
19,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_X,51706,416.187794,88517.020885,0.000,2.011786e+07
20,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_X,51706,416.187794,88517.020885,0.000,2.011786e+07
21,http://iot.uni-trier.de/FTOnto#HBW_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,51706,416.187794,88517.020885,0.000,2.011786e+07
22,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_Task_Elapsed_Seconds_Since_Start,51706,416.187794,88517.020885,0.000,2.011786e+07
23,http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_2:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,51706,416.187794,88517.020885,0.000,2.011786e+07
24,http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_8:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,51706,416.187794,88517.020885,0.000,2.011786e+07
25,http://iot.uni-trier.de/FTOnto#HBW_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,51706,416.187794,88517.020885,0.000,2.011786e+07
26,http://iot.uni-trier.de/FTOnto#HBW_1_Position_Switch_7:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,51706,416.187794,88517.020885,0.000,2.011786e+07
27,http://iot.uni-trier.de/FTOnto#HBW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_Y,51706,416.187794,88517.020885,0.000,2.011786e+07
28,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Magnetic_Field_Strength,17441994,0.074867,152.907355,0.000,4.247437e+05
29,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,17826751,0.073251,151.248242,0.000,4.247437e+05
30,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_2:http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation,17896629,0.072965,150.952677,0.000,4.247437e+05

--- Resource: hbw_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
1,"http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_X, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_2:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_4:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_5:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_6:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_7:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_8:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",1063,19134,18
3,"http://iot.uni-trier.de/FTOnto#HBW_2_Slot_1:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_2:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_3:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_4:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_5:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_6:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_7:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_8:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_9:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Waiting_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID",78,780,10
2,"http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_X, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_Y, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_2:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Motor_4:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_5:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_6:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_7:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_8:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_1:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_2:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_3:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_4:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_5:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_6:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_7:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_8:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Slot_9:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#HBW_2_Waiting_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID",3,84,28
0,"http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_Y",1,2,2

Time Intervals Analysis for hbw_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_6:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
1,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_3:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
2,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_5:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
3,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_2:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
4,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_9:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
5,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_7:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
6,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_8:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
7,http://iot.uni-trier.de/FTOnto#HBW_2_Waiting_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
8,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_1:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
9,http://iot.uni-trier.de/FTOnto#HBW_2_Slot_4:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,8074,2665.318237,223989.665907,0.0,2.011792e+07
10,http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,97383,220.980869,64499.884483,0.0,2.011791e+07
11,http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,97383,220.980869,64499.884483,0.0,2.011791e+07
12,http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_8:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,97383,220.980869,64499.884483,0.0,2.011791e+07
13,http://iot.uni-trier.de/FTOnto#HBW_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,97383,220.980869,64499.884483,0.0,2.011791e+07
14,http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,97383,220.980869,64499.884483,0.0,2.011791e+07
15,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_X,97383,220.980869,64499.884483,0.0,2.011791e+07
16,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_State,97383,220.980869,64499.884483,0.0,2.011791e+07
17,http://iot.uni-trier.de/FTOnto#HBW_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,97383,220.980869,64499.884483,0.0,2.011791e+07
18,http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_6:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,97383,220.980869,64499.884483,0.0,2.011791e+07
19,http://iot.uni-trier.de/FTOnto#HBW_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,97383,220.980869,64499.884483,0.0,2.011791e+07
20,http://iot.uni-trier.de/FTOnto#HBW_2_Motor_4:http://iot.uni-trier.de/FTOnto#MotorSpeed,97383,220.980869,64499.884483,0.0,2.011791e+07
21,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_Y,97383,220.980869,64499.884483,0.0,2.011791e+07
22,http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_5:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,97383,220.980869,64499.884483,0.0,2.011791e+07
23,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_Task_Elapsed_Seconds_Since_Start,97383,220.980869,64499.884483,0.0,2.011791e+07
24,http://iot.uni-trier.de/FTOnto#HBW_2_Position_Switch_7:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,97383,220.980869,64499.884483,0.0,2.011791e+07
25,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_X,97383,220.980869,64499.884483,0.0,2.011791e+07
26,http://iot.uni-trier.de/FTOnto#HBW_2_Light_Barrier_2:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,97383,220.980869,64499.884483,0.0,2.011791e+07
27,http://iot.uni-trier.de/FTOnto#HBW_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_Y,97383,220.980869,64499.884483,0.0,2.011791e+07

--- Resource: mm_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
2,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_4:http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8_Vibration,14219,14219,1
0,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_3:http://iot.uni-trier.de/FTOnto#MM_1_Motor_3_Vibration,5402,5402,1
3,"http://iot.uni-trier.de/FTOnto#MM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#MM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#MM_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#MM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",32,352,11
1,"http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_3:http://iot.uni-trier.de/FTOnto#MM_1_Motor_3_Vibration, http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_4:http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8_Vibration",13,26,2
4,http://iot.uni-trier.de/FTOnto#MM_1_Turntable:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,1,1,1

Time Intervals Analysis for mm_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#MM_1_Turntable:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,347,61982.638484,1.079943e+06,2.125,2.014001e+07
1,http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
2,http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
3,http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
4,http://iot.uni-trier.de/FTOnto#MM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
5,http://iot.uni-trier.de/FTOnto#MM_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
6,http://iot.uni-trier.de/FTOnto#MM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
7,http://iot.uni-trier.de/FTOnto#MM_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
8,http://iot.uni-trier.de/FTOnto#MM_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
9,http://iot.uni-trier.de/FTOnto#MM_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
10,http://iot.uni-trier.de/FTOnto#MM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_State,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
11,http://iot.uni-trier.de/FTOnto#MM_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,10703,2009.528339,1.947619e+05,0.000,2.014001e+07
12,http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#MM_1_Pneumatic_System_Pressure,36242,36.014477,3.365468e+03,0.000,4.249627e+05
13,http://iot.uni-trier.de/FTOnto#MM_1:http://iot.uni-trier.de/FTOnto#MM_1_Temperature,36268,35.988658,3.364261e+03,0.000,4.249626e+05
14,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_3:http://iot.uni-trier.de/FTOnto#MM_1_Motor_3_Vibration,3627884,0.359779,3.354804e+02,0.000,4.249625e+05
15,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_4:http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8_Vibration,3636380,0.358939,3.350883e+02,0.000,4.249625e+05

--- Resource: sm_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
2,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8_Vibration,11599,11599,1
0,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#SM_1_Motor_1_Vibration,7392,7392,1
8,http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#SM_1_Pneumatic_System_Pressure,106,106,1
4,http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/FTOnto#SM_1_Temperature,106,106,1
7,"http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#SM_1_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection, http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#SM_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",54,756,13
1,"http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#SM_1_Motor_1_Vibration, http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8_Vibration",9,18,2
9,http://iot.uni-trier.de/FTOnto#SM_1_Conveyor_Belt:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,2,2,1
5,"http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/FTOnto#SM_1_Temperature, http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#SM_1_Pneumatic_System_Pressure",2,4,2
3,"http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8_Vibration, http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/FTOnto#SM_1_Temperature",1,2,2
6,"http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#SM_1_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection, http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#SM_1_Pneumatic_System_Pressure, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#SM_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",1,15,14

Time Intervals Analysis for sm_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#SM_1_Conveyor_Belt:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,346,62161.759312,1.081901e+06,0.053,2.014747e+07
1,http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
2,http://iot.uni-trier.de/FTOnto#SM_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
3,http://iot.uni-trier.de/FTOnto#SM_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
4,http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
5,http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
6,http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
7,http://iot.uni-trier.de/FTOnto#SM_1_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
8,http://iot.uni-trier.de/FTOnto#SM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
9,http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
10,http://iot.uni-trier.de/FTOnto#SM_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
11,http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
12,http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_State,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
13,NaN,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
14,http://iot.uni-trier.de/FTOnto#SM_1_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,10179,2112.975060,1.997857e+05,0.096,2.014747e+07
15,http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8:http://iot.uni-trier.de/FTOnto#SM_1_Pneumatic_System_Pressure,35670,36.597655,3.398142e+03,0.000,4.265689e+05
16,http://iot.uni-trier.de/FTOnto#SM_1:http://iot.uni-trier.de/FTOnto#SM_1_Temperature,35672,36.595603,3.398046e+03,0.000,4.265689e+05
17,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#SM_1_Motor_1_Vibration,2537577,0.514443,4.018188e+02,0.000,4.265689e+05
18,http://iot.uni-trier.de/FTOnto#ADXL345_Pi_1_AccSensor_2:http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8_Vibration,3487414,0.374329,3.427585e+02,0.000,4.265689e+05

--- Resource: wt_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
0,"http://iot.uni-trier.de/FTOnto#OV_2_WT_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#WT_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#WT_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#WT_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#WT_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_2_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_2_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#WT_2_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen",2500,20000,8

Time Intervals Analysis for wt_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#WT_2_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen,29411,731.64707,117490.280669,0.0,2.013933e+07
1,http://iot.uni-trier.de/FTOnto#WT_2_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,29411,731.64707,117490.280669,0.0,2.013933e+07
2,http://iot.uni-trier.de/FTOnto#WT_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_Task_Elapsed_Seconds_Since_Start,29411,731.64707,117490.280669,0.0,2.013933e+07
3,http://iot.uni-trier.de/FTOnto#WT_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_State,29411,731.64707,117490.280669,0.0,2.013933e+07
4,http://iot.uni-trier.de/FTOnto#WT_2_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen,29411,731.64707,117490.280669,0.0,2.013933e+07
5,http://iot.uni-trier.de/FTOnto#WT_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,29411,731.64707,117490.280669,0.0,2.013933e+07
6,http://iot.uni-trier.de/FTOnto#OV_2_WT_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,29411,731.64707,117490.280669,0.0,2.013933e+07
7,http://iot.uni-trier.de/FTOnto#WT_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,29411,731.64707,117490.280669,0.0,2.013933e+07

--- Resource: ov_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
8,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure,2198,6178,1
0,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature,2056,3260,1
5,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel",1226,9808,8
3,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure",252,504,2
7,http://iot.uni-trier.de/FTOnto#OV_1_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,42,42,1
1,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel",11,99,9
6,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure",9,81,9
4,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel",2,18,9
2,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure",1,10,10

Time Intervals Analysis for ov_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#OV_1_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,1247,17256.248265,569751.080826,0.0,2.011855e+07
1,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,34508,623.581394,108355.339894,0.0,2.011855e+07
2,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start,34508,623.581394,108355.339894,0.0,2.011855e+07
3,http://iot.uni-trier.de/FTOnto#OV_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,34508,623.581394,108355.339894,0.0,2.011855e+07
4,http://iot.uni-trier.de/FTOnto#OV_1_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,34508,623.581394,108355.339894,0.0,2.011855e+07
5,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State,34508,623.581394,108355.339894,0.0,2.011855e+07
6,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,34508,623.581394,108355.339894,0.0,2.011855e+07
7,http://iot.uni-trier.de/FTOnto#OV_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,34508,623.581394,108355.339894,0.0,2.011855e+07
8,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,34508,623.581394,108355.339894,0.0,2.011855e+07
9,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature,118226,11.042317,1863.180519,0.0,4.247191e+05
10,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure,118229,11.042036,1863.156815,0.0,4.247190e+05

--- Resource: vgr_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
0,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Acceleration,10352,10352,1
2,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Magnetic_Field_Strength,8506,8506,1
3,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/FTOnto#VGR_1_Temperature,109,109,1
6,http://iot.uni-trier.de/FTOnto#VGR_1_Compressor_7:http://iot.uni-trier.de/FTOnto#VGR_1_Pneumatic_System_Pressure,109,109,1
5,"http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Y, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Z, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_X, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Y, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Z, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#VGR_1_Compressor_7:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#VGR_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_1_Valve_8:http://iot.uni-trier.de/FTOnto#ValveOpen",57,912,16
4,"http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/FTOnto#VGR_1_Temperature, http://iot.uni-trier.de/FTOnto#VGR_1_Compressor_7:http://iot.uni-trier.de/FTOnto#VGR_1_Pneumatic_System_Pressure",4,8,2
1,"http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Acceleration, http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Magnetic_Field_Strength",2,4,2

Time Intervals Analysis for vgr_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Y,85350,252.120999,68896.810584,0.0,2.011795e+07
1,http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,85350,252.120999,68896.810584,0.0,2.011795e+07
2,http://iot.uni-trier.de/FTOnto#VGR_1_Compressor_7:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,85350,252.120999,68896.810584,0.0,2.011795e+07
3,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Z,85350,252.120999,68896.810584,0.0,2.011795e+07
4,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_Task_Elapsed_Seconds_Since_Start,85350,252.120999,68896.810584,0.0,2.011795e+07
5,http://iot.uni-trier.de/FTOnto#VGR_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,85350,252.120999,68896.810584,0.0,2.011795e+07
6,http://iot.uni-trier.de/FTOnto#VGR_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,85350,252.120999,68896.810584,0.0,2.011795e+07
7,http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,85350,252.120999,68896.810584,0.0,2.011795e+07
8,http://iot.uni-trier.de/FTOnto#VGR_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,85350,252.120999,68896.810584,0.0,2.011795e+07
9,http://iot.uni-trier.de/FTOnto#VGR_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,85350,252.120999,68896.810584,0.0,2.011795e+07
10,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_X,85350,252.120999,68896.810584,0.0,2.011795e+07
11,http://iot.uni-trier.de/FTOnto#VGR_1_Valve_8:http://iot.uni-trier.de/FTOnto#ValveOpen,85350,252.120999,68896.810584,0.0,2.011795e+07
12,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Y,85350,252.120999,68896.810584,0.0,2.011795e+07
13,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Z,85350,252.120999,68896.810584,0.0,2.011795e+07
14,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_State,85350,252.120999,68896.810584,0.0,2.011795e+07
15,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_X,85350,252.120999,68896.810584,0.0,2.011795e+07
16,http://iot.uni-trier.de/FTOnto#VGR_1_Compressor_7:http://iot.uni-trier.de/FTOnto#VGR_1_Pneumatic_System_Pressure,318652,4.098709,1133.395674,0.0,4.245153e+05
17,http://iot.uni-trier.de/FTOnto#VGR_1:http://iot.uni-trier.de/FTOnto#VGR_1_Temperature,318668,4.098503,1133.367231,0.0,4.245153e+05
18,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Rotation,15171646,0.086086,163.838716,0.0,4.245153e+05
19,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Magnetometer_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Magnetic_Field_Strength,15777029,0.082783,160.648341,0.0,4.245153e+05
20,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_1:http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Acceleration,16083843,0.081203,159.108706,0.0,4.245153e+05

--- Resource: ov_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
2,"http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_2_WT_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel",2458,19664,8
3,http://iot.uni-trier.de/FTOnto#OV_2_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,213,213,1
1,"http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_2_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#OV_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#OV_2_WT_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel",13,117,9
0,"http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#OV_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#OV_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",1,6,6

Time Intervals Analysis for ov_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#OV_2_Transport_Platform:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,1528,14082.768076,514734.476863,0.046,2.011806e+07
1,http://iot.uni-trier.de/FTOnto#OV_2_WT_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,18245,1179.417536,149012.207220,0.109,2.011806e+07
2,http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State,18245,1179.417536,149012.207220,0.109,2.011806e+07
3,http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,18245,1179.417536,149012.207220,0.109,2.011806e+07
4,http://iot.uni-trier.de/FTOnto#OV_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,18245,1179.417536,149012.207220,0.109,2.011806e+07
5,http://iot.uni-trier.de/FTOnto#OV_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,18245,1179.417536,149012.207220,0.109,2.011806e+07
6,http://iot.uni-trier.de/FTOnto#OV_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,18245,1179.417536,149012.207220,0.109,2.011806e+07
7,http://iot.uni-trier.de/FTOnto#OV_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,18245,1179.417536,149012.207220,0.109,2.011806e+07
8,http://iot.uni-trier.de/FTOnto#OV_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_Task_Elapsed_Seconds_Since_Start,18245,1179.417536,149012.207220,0.109,2.011806e+07

--- Resource: mm_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
1,"http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#MM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#MM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#MM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",1801,19811,11
3,http://iot.uni-trier.de/FTOnto#MM_2_Turntable:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,114,114,1
0,"http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#MM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#MM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#MM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#MM_2_Turntable:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#MM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",6,72,12
2,"http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",1,3,3

Time Intervals Analysis for mm_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#MM_2_Turntable:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,559,38475.783562,851690.647476,1.360,2.014700e+07
1,http://iot.uni-trier.de/FTOnto#MM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8210,2619.727619,222448.126704,0.118,2.014700e+07
2,http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,8210,2619.727619,222448.126704,0.118,2.014700e+07
3,http://iot.uni-trier.de/FTOnto#MM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,8210,2619.727619,222448.126704,0.118,2.014700e+07
4,http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,8210,2619.727619,222448.126704,0.118,2.014700e+07
5,http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,8210,2619.727619,222448.126704,0.118,2.014700e+07
6,http://iot.uni-trier.de/FTOnto#MM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,8210,2619.727619,222448.126704,0.118,2.014700e+07
7,http://iot.uni-trier.de/FTOnto#MM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,8210,2619.727619,222448.126704,0.118,2.014700e+07
8,http://iot.uni-trier.de/FTOnto#MM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,8210,2619.727619,222448.126704,0.118,2.014700e+07
9,http://iot.uni-trier.de/FTOnto#MM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,8210,2619.727619,222448.126704,0.118,2.014700e+07
10,http://iot.uni-trier.de/FTOnto#MM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State,8210,2619.727619,222448.126704,0.118,2.014700e+07
11,http://iot.uni-trier.de/FTOnto#MM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,8210,2619.727619,222448.126704,0.118,2.014700e+07

--- Resource: dm_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
1,"http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_6:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_7:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_8:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",1415,19810,14
3,http://iot.uni-trier.de/FTOnto#DM_2_Sink:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,98,98,1
2,"http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_6:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_7:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_8:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#DM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#DM_2_Sink:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID",6,90,15
0,"http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_Task_Elapsed_Seconds_Since_Start",1,2,2

Time Intervals Analysis for dm_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#DM_2_Sink:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,430,3036.394988,30692.689871,0.046,425058.243
1,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,5767,226.400665,8418.731706,0.108,425053.244
2,http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State,5767,226.400665,8418.731706,0.108,425053.244
3,http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_7:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,5767,226.400665,8418.731706,0.108,425053.244
4,http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_6:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,5767,226.400665,8418.731706,0.108,425053.244
5,http://iot.uni-trier.de/FTOnto#DM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,5767,226.400665,8418.731706,0.108,425053.244
6,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,5767,226.400665,8418.731706,0.108,425053.244
7,http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,5767,226.400665,8418.731706,0.108,425053.244
8,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,5767,226.400665,8418.731706,0.108,425053.244
9,http://iot.uni-trier.de/FTOnto#DM_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,5767,226.400665,8418.731706,0.108,425053.244
10,http://iot.uni-trier.de/FTOnto#DM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,5767,226.400665,8418.731706,0.108,425053.244
11,http://iot.uni-trier.de/FTOnto#DM_2_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,5767,226.400665,8418.731706,0.108,425053.244
12,http://iot.uni-trier.de/FTOnto#DM_2_Capacitive_Sensor_8:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,5767,226.400665,8418.731706,0.108,425053.244
13,http://iot.uni-trier.de/FTOnto#DM_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,5767,226.400665,8418.731706,0.108,425053.244
14,http://iot.uni-trier.de/FTOnto#DM_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,5767,226.400665,8418.731706,0.108,425053.244

--- Resource: pm_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
1,"http://iot.uni-trier.de/FTOnto#PM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#PM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_6:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_7:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_8:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed, http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#PM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#PM_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#PM_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed",1425,19950,14
2,http://iot.uni-trier.de/FTOnto#PM_1_Sink:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,49,49,1
0,http://iot.uni-trier.de/FTOnto#PM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State,1,1,1

Time Intervals Analysis for pm_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#PM_1_Sink:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,310,4206.566974,36174.36791,3.133,426849.583
1,http://iot.uni-trier.de/FTOnto#PM_1_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,9290,140.370302,6650.98377,0.001,426844.370
2,http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,9290,140.370302,6650.98377,0.001,426844.370
3,http://iot.uni-trier.de/FTOnto#PM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State,9290,140.370302,6650.98377,0.001,426844.370
4,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,9290,140.370302,6650.98377,0.001,426844.370
5,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_5:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,9290,140.370302,6650.98377,0.001,426844.370
6,http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_6:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,9290,140.370302,6650.98377,0.001,426844.370
7,http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_8:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,9290,140.370302,6650.98377,0.001,426844.370
8,http://iot.uni-trier.de/FTOnto#PM_1_Capacitive_Sensor_7:http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,9290,140.370302,6650.98377,0.001,426844.370
9,http://iot.uni-trier.de/FTOnto#PM_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,9290,140.370302,6650.98377,0.001,426844.370
10,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_4:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,9290,140.370302,6650.98377,0.001,426844.370
11,http://iot.uni-trier.de/FTOnto#PM_1_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,9290,140.370302,6650.98377,0.001,426844.370
12,http://iot.uni-trier.de/FTOnto#PM_1_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,9290,140.370302,6650.98377,0.001,426844.370
13,http://iot.uni-trier.de/FTOnto#PM_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,9290,140.370302,6650.98377,0.001,426844.370
14,http://iot.uni-trier.de/FTOnto#PM_1_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,9290,140.370302,6650.98377,0.001,426844.370

--- Resource: wt_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
5,"http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#WT_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#WT_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen",1982,15856,8
6,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure,1653,1653,1
0,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature,1653,1653,1
3,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure",209,418,2
4,"http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#WT_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#WT_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen",21,189,9
2,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#WT_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#WT_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen",19,171,9
1,"http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#WT_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#WT_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#WT_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen",6,60,10

Time Intervals Analysis for wt_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#WT_1_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,35157,612.068438,107350.603206,0.023,2.011854e+07
1,http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,35157,612.068438,107350.603206,0.023,2.011854e+07
2,http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start,35157,612.068438,107350.603206,0.023,2.011854e+07
3,http://iot.uni-trier.de/FTOnto#WT_1_Position_Switch_4:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,35157,612.068438,107350.603206,0.023,2.011854e+07
4,http://iot.uni-trier.de/FTOnto#WT_1_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen,35157,612.068438,107350.603206,0.023,2.011854e+07
5,http://iot.uni-trier.de/FTOnto#WT_1_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen,35157,612.068438,107350.603206,0.023,2.011854e+07
6,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,35157,612.068438,107350.603206,0.023,2.011854e+07
7,http://iot.uni-trier.de/FTOnto#WT_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State,35157,612.068438,107350.603206,0.023,2.011854e+07
8,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Compressor_8:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure,65019,20.077799,2513.070367,0.000,4.246205e+05
9,http://iot.uni-trier.de/FTOnto#OV_1:http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature,65054,20.066995,2512.393865,0.000,4.246204e+05

--- Resource: sm_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
1,"http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#SM_2_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection, http://iot.uni-trier.de/FTOnto#SM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#SM_2_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_2_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",1424,19936,13
3,http://iot.uni-trier.de/FTOnto#SM_2_Conveyor_Belt:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,28,28,1
0,"http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#SM_2_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection, http://iot.uni-trier.de/FTOnto#SM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#SM_2_Conveyor_Belt:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#SM_2_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_2_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen, http://iot.uni-trier.de/FTOnto#SM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen",2,30,14
2,"http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#SM_2_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted",1,6,5

Time Intervals Analysis for sm_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#SM_2_Conveyor_Belt:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,566,2307.214124,26769.561908,1.219,425057.088
1,NaN,8191,159.429408,7061.115667,0.129,425054.245
2,http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_1:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8191,159.429408,7061.115667,0.129,425054.245
3,http://iot.uni-trier.de/FTOnto#SM_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,8191,159.429408,7061.115667,0.129,425054.245
4,http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State,8191,159.429408,7061.115667,0.129,425054.245
5,http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8191,159.429408,7061.115667,0.129,425054.245
6,http://iot.uni-trier.de/FTOnto#SM_2_Valve_6:http://iot.uni-trier.de/FTOnto#ValveOpen,8191,159.429408,7061.115667,0.129,425054.245
7,http://iot.uni-trier.de/FTOnto#SM_2_Compressor_8:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,8191,159.429408,7061.115667,0.129,425054.245
8,http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_3:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8191,159.429408,7061.115667,0.129,425054.245
9,http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_7:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8191,159.429408,7061.115667,0.129,425054.245
10,http://iot.uni-trier.de/FTOnto#SM_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,8191,159.429408,7061.115667,0.129,425054.245
11,http://iot.uni-trier.de/FTOnto#SM_2_Valve_5:http://iot.uni-trier.de/FTOnto#ValveOpen,8191,159.429408,7061.115667,0.129,425054.245
12,http://iot.uni-trier.de/FTOnto#SM_2_Color_Sensor_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection,8191,159.429408,7061.115667,0.129,425054.245
13,http://iot.uni-trier.de/FTOnto#SM_2_Light_Barrier_6:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,8191,159.429408,7061.115667,0.129,425054.245
14,http://iot.uni-trier.de/FTOnto#SM_2_Valve_7:http://iot.uni-trier.de/FTOnto#ValveOpen,8191,159.429408,7061.115667,0.129,425054.245

--- Resource: vgr_2 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
0,"http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_X, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Y, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Z, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_X, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Y, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Z, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_State, http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#VGR_2_Compressor_7:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel, http://iot.uni-trier.de/FTOnto#VGR_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed, http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed, http://iot.uni-trier.de/FTOnto#VGR_2_Valve_8:http://iot.uni-trier.de/FTOnto#ValveOpen",1250,20000,16

Time Intervals Analysis for vgr_2:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Y,52961,406.309972,87462.906667,0.0,2.011807e+07
1,http://iot.uni-trier.de/FTOnto#VGR_2_Motor_1:http://iot.uni-trier.de/FTOnto#MotorSpeed,52961,406.309972,87462.906667,0.0,2.011807e+07
2,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_X,52961,406.309972,87462.906667,0.0,2.011807e+07
3,http://iot.uni-trier.de/FTOnto#VGR_2_Compressor_7:http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,52961,406.309972,87462.906667,0.0,2.011807e+07
4,http://iot.uni-trier.de/FTOnto#VGR_2_Motor_2:http://iot.uni-trier.de/FTOnto#MotorSpeed,52961,406.309972,87462.906667,0.0,2.011807e+07
5,http://iot.uni-trier.de/FTOnto#VGR_2_Valve_8:http://iot.uni-trier.de/FTOnto#ValveOpen,52961,406.309972,87462.906667,0.0,2.011807e+07
6,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Z,52961,406.309972,87462.906667,0.0,2.011807e+07
7,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_Task_Elapsed_Seconds_Since_Start,52961,406.309972,87462.906667,0.0,2.011807e+07
8,http://iot.uni-trier.de/FTOnto#VGR_2_Motor_3:http://iot.uni-trier.de/FTOnto#MotorSpeed,52961,406.309972,87462.906667,0.0,2.011807e+07
9,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Y,52961,406.309972,87462.906667,0.0,2.011807e+07
10,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_X,52961,406.309972,87462.906667,0.0,2.011807e+07
11,http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_2:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,52961,406.309972,87462.906667,0.0,2.011807e+07
12,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Z,52961,406.309972,87462.906667,0.0,2.011807e+07
13,http://iot.uni-trier.de/FTOnto#VGR_2:http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_State,52961,406.309972,87462.906667,0.0,2.011807e+07
14,http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_3:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,52961,406.309972,87462.906667,0.0,2.011807e+07
15,http://iot.uni-trier.de/FTOnto#VGR_2_Position_Switch_1:http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,52961,406.309972,87462.906667,0.0,2.011807e+07

--- Resource: hw_1 ---

,sensor_group,timestamp_count,total_occurrences,num_sensors
0,"http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HW_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_6:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed, http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_7:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed",3981,19905,5
3,http://iot.uni-trier.de/FTOnto#HW_1_Workplace:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,68,68,1
1,"http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HW_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted, http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_6:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed, http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_7:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed, http://iot.uni-trier.de/FTOnto#HW_1_Workplace:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID",4,24,6
2,"http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State, http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_Task_Elapsed_Seconds_Since_Start, http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_6:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed",1,3,3

Time Intervals Analysis for hw_1:

,sensor,total_readings,avg_interval_seconds,stddev_interval_seconds,min_interval_seconds,max_interval_seconds
0,http://iot.uni-trier.de/FTOnto#HW_1_Workplace:http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,762,1712.934475,23098.038041,0.047,425013.700
1,http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_6:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed,38729,33.717707,3246.188158,0.019,424882.653
2,http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State,38729,33.717707,3246.188158,0.019,424882.653
3,http://iot.uni-trier.de/FTOnto#HW_1_Manual_Switch_7:http://iot.uni-trier.de/FTOnto#ManualSwitchPressed,38729,33.717707,3246.188158,0.019,424882.653
4,http://iot.uni-trier.de/FTOnto#HW_1_Light_Barrier_8:http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,38729,33.717707,3246.188158,0.019,424882.653
5,http://iot.uni-trier.de/FTOnto#HW_1:http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_Task_Elapsed_Seconds_Since_Start,38729,33.717707,3246.188158,0.019,424882.653

Get the form of all multidimensional sensor values (like position)

In [ ]:
df = con.execute("""
    SELECT 
        "stream:value",
        "stream:observation",
        "stream:system"
    FROM sensor_data
    WHERE "stream:procedure_type" = 'stream:continuous'
    GROUP BY "stream:value", "stream:observation", "stream:system", "stream:procedure_type"
""").df()

# Filter to keep only non-numerical values
df['_num'] = pd.to_numeric(df['stream:value'], errors='coerce')
df = df[df['_num'].isna()].drop(columns=['_num'])

display(df)

,stream:value,stream:observation,stream:system
1,"[-0.3662, -31.8995, -15.6713]",http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Rotation,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_1
2,"[0.846, -10.556, -1.1248]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
3,"[-0.8268, -10.4214, 0.5672]",http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_1
4,"[-2.615, -10.1041, -1.3555]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
5,"[1.9997, -16.853, 4.0378]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
...,...,...,...
30766763,"[0.6441, -10.9886, -0.4807]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
30766764,"[-10.445, 0.9919, -3.7461]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_2
30766765,"[-0.5191, -11.5366, 1.2498]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
30766766,"[0.5384, -8.4313, 0.2115]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_AccSensor_2
30766767,"[-4.4481, -2.2202, 1.1902]",http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation,http://iot.uni-trier.de/FTOnto#BMX055_Pi_1_Gyroscope_2

List all possible observations of sensors

In [ ]:
df_observations = con.execute("""
    SELECT
        "stream:observation",
        first("stream:value" ORDER BY "stream:timestamp") AS "example value",
        list(DISTINCT "stream:system_type" ORDER BY "stream:system_type") AS system_types,
        list(DISTINCT "stream:procedure_type" ORDER BY "stream:procedure_type") AS procedure_types,
        list(DISTINCT "org:resource" ORDER BY "org:resource") AS resources
    FROM sensor_data
    WHERE "stream:observation" IS NOT NULL
    GROUP BY "stream:observation"
    ORDER BY "stream:observation"
""").df()

pd.set_option('display.max_rows', None)
display(df_observations)

,stream:observation,example value,system_types,procedure_types,resources
0,http://iot.uni-trier.de/FTOnto#CompressorPowerLevel,0.0,[sosa:Actuator],[stream:continuous],"[mm_1, mm_2, ov_1, ov_2, sm_1, sm_2, vgr_1, vgr_2, wt_1, wt_2]"
1,http://iot.uni-trier.de/FTOnto#Electric_Field_Changed,0.0,[sosa:Sensor],[stream:binary],"[dm_2, pm_1]"
2,http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Acceleration,"[0.7691, -9.9695, 0.1923]",[sosa:Sensor],[stream:continuous],[hbw_1]
3,http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Magnetic_Field_Strength,"[49.6682, 17.1785, -9.3233]",[sosa:Sensor],[stream:continuous],[hbw_1]
4,http://iot.uni-trier.de/FTOnto#HBW_1_Crane_Jib_Rotation,"[4.7533, -2.2202, -5.295]",[sosa:Sensor],[stream:continuous],[hbw_1]
5,http://iot.uni-trier.de/FTOnto#LightBarrierInterrupted,0.0,[sosa:Sensor],[stream:binary],"[dm_2, hbw_1, hbw_2, hw_1, mm_1, mm_2, ov_1, ov_2, pm_1, sm_1, sm_2]"
6,http://iot.uni-trier.de/FTOnto#MM_1_Compressor_8_Vibration,"[0.5494, -0.0785, 10.0454]",[sosa:Sensor],[stream:continuous],[mm_1]
7,http://iot.uni-trier.de/FTOnto#MM_1_Motor_3_Vibration,"[0.0, 0.0, 8.1619]",[sosa:Sensor],[stream:continuous],[mm_1]
8,http://iot.uni-trier.de/FTOnto#MM_1_Pneumatic_System_Pressure,671.0696044989999,[sosa:Sensor],[stream:continuous],[mm_1]
9,http://iot.uni-trier.de/FTOnto#MM_1_Temperature,27.577,[sosa:Sensor],[stream:continuous],[mm_1]
10,http://iot.uni-trier.de/FTOnto#ManualSwitchPressed,0.0,[sosa:Sensor],[stream:binary],[hw_1]
11,http://iot.uni-trier.de/FTOnto#MotorSpeed,0.0,[sosa:Actuator],[stream:continuous],"[dm_2, hbw_1, hbw_2, mm_1, mm_2, ov_1, ov_2, pm_1, sm_1, sm_2, vgr_1, vgr_2, wt_1, wt_2]"
12,http://iot.uni-trier.de/FTOnto#NFC_Tag_UID,6cde5431,[sosa:Sensor],[stream:discrete],"[dm_2, hbw_1, hbw_2, hw_1, mm_1, mm_2, ov_1, ov_2, pm_1, sm_1, sm_2]"
13,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Pneumatic_System_Pressure,669.3006022359999,[sosa:Sensor],[stream:continuous],"[ov_1, wt_1]"
14,http://iot.uni-trier.de/FTOnto#OV_1_WT_1_Temperature,27.772,[sosa:Sensor],[stream:continuous],"[ov_1, wt_1]"
15,http://iot.uni-trier.de/FTOnto#PositionSwitchPressed,1.0,[sosa:Sensor],[stream:binary],"[dm_2, hbw_1, hbw_2, mm_1, mm_2, ov_1, ov_2, pm_1, vgr_1, vgr_2, wt_1, wt_2]"
16,http://iot.uni-trier.de/FTOnto#SM_1_Compressor_8_Vibration,"[0.0, 0.3139, 9.0252]",[sosa:Sensor],[stream:continuous],[sm_1]
17,http://iot.uni-trier.de/FTOnto#SM_1_Motor_1_Vibration,"[0.8633, -1.8835, 8.0834]",[sosa:Sensor],[stream:continuous],[sm_1]
18,http://iot.uni-trier.de/FTOnto#SM_1_Pneumatic_System_Pressure,668.4020614039998,[sosa:Sensor],[stream:continuous],[sm_1]
19,http://iot.uni-trier.de/FTOnto#SM_1_Temperature,27.772,[sosa:Sensor],[stream:continuous],[sm_1]
20,http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Acceleration,"[-1.5478, -9.335, 1.0287]",[sosa:Sensor],[stream:continuous],[vgr_1]
21,http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Magnetic_Field_Strength,"[8.1762, 54.2601, 33.9471]",[sosa:Sensor],[stream:continuous],[vgr_1]
22,http://iot.uni-trier.de/FTOnto#VGR_1_Crane_Jib_Rotation,"[-0.2213, -2.6399, 9.2776]",[sosa:Sensor],[stream:continuous],[vgr_1]
23,http://iot.uni-trier.de/FTOnto#VGR_1_Pneumatic_System_Pressure,1902.7782904698433,[sosa:Sensor],[stream:continuous],[vgr_1]
24,http://iot.uni-trier.de/FTOnto#VGR_1_Temperature,35.002,[sosa:Sensor],[stream:continuous],[vgr_1]
25,http://iot.uni-trier.de/FTOnto#ValveOpen,0.0,[sosa:Actuator],[stream:binary],"[mm_1, mm_2, ov_1, ov_2, sm_1, sm_2, vgr_1, vgr_2, wt_1, wt_2]"
26,http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[dm_2]
27,http://iot.uni-trier.de/StreamDataAnnotationOnto#DM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.265635,[sosa:Sensor],[stream:continuous],[dm_2]
28,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_X,4.20,[sosa:Sensor],[stream:continuous],[hbw_1]
29,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Current_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[hbw_1]
30,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_X,295.66,[sosa:Sensor],[stream:continuous],[hbw_1]
31,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Crane_Jib_Property_Target_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[hbw_1]
32,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[hbw_1]
33,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.250061,[sosa:Sensor],[stream:continuous],[hbw_1]
34,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_X,2.40,[sosa:Sensor],[stream:continuous],[hbw_2]
35,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Current_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[hbw_2]
36,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_X,297.91,[sosa:Sensor],[stream:continuous],[hbw_2]
37,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Crane_Jib_Property_Target_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[hbw_2]
38,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[hbw_2]
39,http://iot.uni-trier.de/StreamDataAnnotationOnto#HBW_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.172219,[sosa:Sensor],[stream:continuous],[hbw_2]
40,http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[hw_1]
41,http://iot.uni-trier.de/StreamDataAnnotationOnto#HW_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.171953,[sosa:Sensor],[stream:continuous],[hw_1]
42,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[mm_1]
43,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.109488,[sosa:Sensor],[stream:continuous],[mm_1]
44,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[mm_2]
45,http://iot.uni-trier.de/StreamDataAnnotationOnto#MM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.124944,[sosa:Sensor],[stream:continuous],[mm_2]
46,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[ov_1]
47,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.109088,[sosa:Sensor],[stream:continuous],[ov_1]
48,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_State,not ready,[sosa:Actuator],[stream:discrete],[ov_2]
49,http://iot.uni-trier.de/StreamDataAnnotationOnto#OV_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.156194,[sosa:Sensor],[stream:continuous],[ov_2]
50,http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[pm_1]
51,http://iot.uni-trier.de/StreamDataAnnotationOnto#PM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.296837,[sosa:Sensor],[stream:continuous],[pm_1]
52,http://iot.uni-trier.de/StreamDataAnnotationOnto#RedLightReflection,1689.0,[sosa:Sensor],[stream:continuous],"[sm_1, sm_2]"
53,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[sm_1]
54,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.141039,[sosa:Sensor],[stream:continuous],[sm_1]
55,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[sm_2]
56,http://iot.uni-trier.de/StreamDataAnnotationOnto#SM_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.29693,[sosa:Sensor],[stream:continuous],[sm_2]
57,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_X,4.64,[sosa:Sensor],[stream:continuous],[vgr_1]
58,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[vgr_1]
59,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Current_Position_Z,0.00,[sosa:Sensor],[stream:continuous],[vgr_1]
60,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_X,4.87,[sosa:Sensor],[stream:continuous],[vgr_1]
61,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[vgr_1]
62,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Crane_Jib_Property_Target_Position_Z,70.99,[sosa:Sensor],[stream:continuous],[vgr_1]
63,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[vgr_1]
64,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.266015,[sosa:Sensor],[stream:continuous],[vgr_1]
65,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_X,2.09,[sosa:Sensor],[stream:continuous],[vgr_2]
66,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[vgr_2]
67,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Current_Position_Z,0.00,[sosa:Sensor],[stream:continuous],[vgr_2]
68,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_X,327.31,[sosa:Sensor],[stream:continuous],[vgr_2]
69,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Y,0.00,[sosa:Sensor],[stream:continuous],[vgr_2]
70,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Crane_Jib_Property_Target_Position_Z,0.00,[sosa:Sensor],[stream:continuous],[vgr_2]
71,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[vgr_2]
72,http://iot.uni-trier.de/StreamDataAnnotationOnto#VGR_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.140627,[sosa:Sensor],[stream:continuous],[vgr_2]
73,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[wt_1]
74,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_1_Property_Current_Task_Elapsed_Seconds_Since_Start,0.203071,[sosa:Sensor],[stream:continuous],[wt_1]
75,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_State,not ready,[sosa:Sensor],[stream:discrete],[wt_2]
76,http://iot.uni-trier.de/StreamDataAnnotationOnto#WT_2_Property_Current_Task_Elapsed_Seconds_Since_Start,0.125209,[sosa:Sensor],[stream:continuous],[wt_2]

Getting the number of values, where Position Sensor 2 is True compared to where Positon sensor 1 is True

In [ ]:
df_sensor_grouped = con.execute("""
    SELECT
        "stream:system",
        "stream:value",
        COUNT(*) AS value_count
    FROM sensor_data
    WHERE "org:resource" = 'ov_1'
        AND "concept:name" = 'transporting the workpiece to the outside of the oven'
        AND "stream:system" ILIKE '%position%'
        AND "stream:value" IS NOT NULL
    GROUP BY "stream:system", "stream:value"
    ORDER BY "stream:system", value_count DESC
""").df()

display(df_sensor_grouped)

,stream:system,stream:value,value_count
0,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1,0.0,2588
1,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1,1.0,227
2,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2,0.0,2743
3,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2,1.0,72

Getting the number of values where position sensor is 0 for tempering the workpiece

In [ ]:
df_sensor_grouped = con.execute("""
    SELECT
        "stream:system",
        "stream:value",
        COUNT(*) AS value_count
    FROM sensor_data
    WHERE "org:resource" = 'ov_1'
        AND "concept:name" = 'temper the workpiece for 40 seconds'
        AND "stream:system" ILIKE '%position%'
        AND "stream:value" IS NOT NULL
    GROUP BY "stream:system", "stream:value"
    ORDER BY "stream:system", value_count DESC
""").df()

display(df_sensor_grouped)

,stream:system,stream:value,value_count
0,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1,1.0,13865
1,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1,0.0,190
2,http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_2,0.0,14055

In [ ]:
df_subprocess_ids = con.execute("""
    SELECT
        "trace:SubProcessID" AS "stream:SubProcessID",
        COUNT(*) AS matches
    FROM sensor_data
    WHERE "org:resource" = 'ov_1'
      AND "concept:name" = 'temper the workpiece for 40 seconds'
      AND "stream:system" = 'http://iot.uni-trier.de/FTOnto#OV_1_Position_Switch_1'
      AND TRY_CAST("stream:value" AS DOUBLE) = 0.0
    GROUP BY "trace:SubProcessID"
    ORDER BY matches DESC, "trace:SubProcessID"
""").df()

display(df_subprocess_ids)

# Optional: only the distinct SubProcessID values as a Python list
subprocess_ids = df_subprocess_ids["stream:SubProcessID"].dropna().tolist()
print(subprocess_ids)

                     stream:SubProcessID  matches
0   082c4fca-2b66-438f-a933-fe1cd4c1b36e      197
1   1e6be670-c66f-42bb-aca2-7c5995fcadb9      197
2   2aee3b24-076d-40ca-ad09-9deb2885d7a1      197
3   3ca03f0e-3c1e-4dbb-bb78-1912b3aa2117      197
4   41531963-a8cb-4f2c-9695-fa3749a6414a      197
5   548415e8-a739-411c-a1aa-aa1dca05d269      197
6   69f24f4d-1851-42d1-b2a1-57ef2aea3fc4      197
7   6fac0fd4-7629-4c87-bcb5-2373812ce14c      197
8   bdaeea16-0f58-4074-ac41-737f1b8210ff      197
9   c1031713-46de-4b94-951b-b56dc1fdd827      197
10  d4de1719-8ba5-4da0-a91a-d239ff43fc1a      197
11  e451ab30-b7c5-4198-b0eb-cfaae439c066      197
12  019f360f-f22c-4526-8f36-d0aae6cc890c      196
13  0871a3e6-157f-451b-b254-8cbd3b1f0592      196
14  1736b385-d5bf-4090-9739-3aef55e51d48      196
15  1a73f4cd-a4a7-4312-8139-08a8732f3816      196
16  248b1c51-b98f-4785-b8c3-bb0f982d4e8d      196
17  27380990-7b3c-4f2e-9475-23b8ca920e73      196
18  3c97f9e6-22f5-4428-bb8e-c3c2648effdd      196
19  3dd56bb8-cebc-4faf-9c27-68e84192e6bc      196
20  43507866-b7ba-43dd-bd6b-98bc77cb583f      196
21  44b44904-3512-40e4-8870-825eb99ca833      196
22  4d232895-9f9c-4ff0-86f7-9c3944922799      196
23  4e3a470e-d84b-4e9a-850c-97814b628f32      196
24  50513203-25e9-4e8c-a745-84b3d259e24e      196
25  509823cd-3688-4a85-bdb0-181b85c7e2ce      196
26  6a3085ef-4912-419e-b59a-178bcdfa67f8      196
27  81102bbe-9df4-4f40-bd68-2328fa25f2dd      196
28  85055f87-90e6-489f-8d6e-265b633eefe7      196
29  8a087bb2-1362-45ec-9df4-f8ba4f1f8c11      196
30  8c805c52-6598-4009-b47c-d4e31c60ebfe      196
31  8ff8a378-9182-4002-b0a4-67c2ef08bfee      196
32  99c47ec4-61ba-4359-871d-806471fe6b4a      196
33  9c3dfd78-2083-4107-9398-30b06c25aded      196
34  a7cc1c08-02d2-440d-92db-3650a060c9ec      196
35  aaa810f8-a75f-41d2-8ea1-a9eb2b7398ab      196
36  ba154c17-5a58-4eb8-ad6b-eb58d620a4d1      196
37  c1b5c77d-1d8e-4108-8a11-7b0473cf5516      196
38  c2806355-6f70-4066-a283-3aded4e0364f      196
39  c575b0b4-43d8-4967-98db-b162531d5341      196
40  dbc17bde-4e22-4271-8655-c06553a532de      196
41  e32e971b-5741-482d-9101-95169442c5cd      196
42  e69120ff-4382-4d63-9cda-598c9d89d55a      196
43  f460b049-13ba-410a-aeae-897e13cdda10      196
44  feac5707-7290-4126-97cd-197121eaaa2f      196
45  001618a4-1be3-406c-bd83-ebe5cff5e4f7      195
46  0312d2d6-88ab-4fa7-a36c-ceff0411b0f4      195
47  0580187d-e0b2-4db7-9089-b52d77066564      195
48  14c40aac-7c60-43c2-928a-5b22ea6e3313      195
49  1aa2359e-8369-49f9-b1f3-7e3df3835fd7      195
50  3901d161-9f23-4c17-9396-726dccaf44eb      195
51  4ba406eb-202f-41a0-8b09-b4654dc5f2f3      195
52  5585e66b-a4e3-4801-b5f8-9f5810c0b7de      195
53  5ce76170-592f-4fcd-a8a8-775f8af8ff2f      195
54  67997114-7b3a-49b6-b800-cc20fef897d1      195
55  77afbfdd-5690-419c-b142-0801c6d029de      195
56  80cb3829-a085-4e5d-94e9-94605916a40a      195
57  b3f19f5b-1f25-4d6b-9c4e-eb8728486513      195
58  bab94ee6-deec-4ec1-9460-081226d8aee7      195
59  c35b15f3-ad39-407b-93ca-41797420de1f      195
60  d0c28319-0add-4845-a2c1-5ecc46a02409      195
61  d4a32b54-731c-4d55-a5be-a96da61e0fe5      195
62  13fdd477-af83-4b82-b91d-d83410b015ec      194
63  24d2b05c-fad9-4377-9c45-63fd406790e2      194
64  95311371-2408-46d8-8284-bc197fc1f192      193
65  b77386e5-8e6b-4a9a-80bf-72ccb8d4c5be      193
66  5d414863-8750-4527-8757-7f9901911c1d      192
67  6de00e45-8fc2-4170-a95d-322857168fb8      192
68  55a58ad9-98c5-4666-97f3-2708320d280d      186
69  35a2a7ff-1450-4fda-933b-e233ae0866de      185
70  f88e6c12-63fe-455c-ac60-c57017e3fe5c      184
71  5ca9cab8-37de-44dc-8b2a-611d03331634        5

['082c4fca-2b66-438f-a933-fe1cd4c1b36e', '1e6be670-c66f-42bb-aca2-7c5995fcadb9', '2aee3b24-076d-40ca-ad09-9deb2885d7a1', '3ca03f0e-3c1e-4dbb-bb78-1912b3aa2117', '41531963-a8cb-4f2c-9695-fa3749a6414a', '548415e8-a739-411c-a1aa-aa1dca05d269', '69f24f4d-1851-42d1-b2a1-57ef2aea3fc4', '6fac0fd4-7629-4c87-bcb5-2373812ce14c', 'bdaeea16-0f58-4074-ac41-737f1b8210ff', 'c1031713-46de-4b94-951b-b56dc1fdd827', 'd4de1719-8ba5-4da0-a91a-d239ff43fc1a', 'e451ab30-b7c5-4198-b0eb-cfaae439c066', '019f360f-f22c-4526-8f36-d0aae6cc890c', '0871a3e6-157f-451b-b254-8cbd3b1f0592', '1736b385-d5bf-4090-9739-3aef55e51d48', '1a73f4cd-a4a7-4312-8139-08a8732f3816', '248b1c51-b98f-4785-b8c3-bb0f982d4e8d', '27380990-7b3c-4f2e-9475-23b8ca920e73', '3c97f9e6-22f5-4428-bb8e-c3c2648effdd', '3dd56bb8-cebc-4faf-9c27-68e84192e6bc', '43507866-b7ba-43dd-bd6b-98bc77cb583f', '44b44904-3512-40e4-8870-825eb99ca833', '4d232895-9f9c-4ff0-86f7-9c3944922799', '4e3a470e-d84b-4e9a-850c-97814b628f32', '50513203-25e9-4e8c-a745-84b3d259e24e', '509823cd-3688-4a85-bdb0-181b85c7e2ce', '6a3085ef-4912-419e-b59a-178bcdfa67f8', '81102bbe-9df4-4f40-bd68-2328fa25f2dd', '85055f87-90e6-489f-8d6e-265b633eefe7', '8a087bb2-1362-45ec-9df4-f8ba4f1f8c11', '8c805c52-6598-4009-b47c-d4e31c60ebfe', '8ff8a378-9182-4002-b0a4-67c2ef08bfee', '99c47ec4-61ba-4359-871d-806471fe6b4a', '9c3dfd78-2083-4107-9398-30b06c25aded', 'a7cc1c08-02d2-440d-92db-3650a060c9ec', 'aaa810f8-a75f-41d2-8ea1-a9eb2b7398ab', 'ba154c17-5a58-4eb8-ad6b-eb58d620a4d1', 'c1b5c77d-1d8e-4108-8a11-7b0473cf5516', 'c2806355-6f70-4066-a283-3aded4e0364f', 'c575b0b4-43d8-4967-98db-b162531d5341', 'dbc17bde-4e22-4271-8655-c06553a532de', 'e32e971b-5741-482d-9101-95169442c5cd', 'e69120ff-4382-4d63-9cda-598c9d89d55a', 'f460b049-13ba-410a-aeae-897e13cdda10', 'feac5707-7290-4126-97cd-197121eaaa2f', '001618a4-1be3-406c-bd83-ebe5cff5e4f7', '0312d2d6-88ab-4fa7-a36c-ceff0411b0f4', '0580187d-e0b2-4db7-9089-b52d77066564', '14c40aac-7c60-43c2-928a-5b22ea6e3313', '1aa2359e-8369-49f9-b1f3-7e3df3835fd7', '3901d161-9f23-4c17-9396-726dccaf44eb', '4ba406eb-202f-41a0-8b09-b4654dc5f2f3', '5585e66b-a4e3-4801-b5f8-9f5810c0b7de', '5ce76170-592f-4fcd-a8a8-775f8af8ff2f', '67997114-7b3a-49b6-b800-cc20fef897d1', '77afbfdd-5690-419c-b142-0801c6d029de', '80cb3829-a085-4e5d-94e9-94605916a40a', 'b3f19f5b-1f25-4d6b-9c4e-eb8728486513', 'bab94ee6-deec-4ec1-9460-081226d8aee7', 'c35b15f3-ad39-407b-93ca-41797420de1f', 'd0c28319-0add-4845-a2c1-5ecc46a02409', 'd4a32b54-731c-4d55-a5be-a96da61e0fe5', '13fdd477-af83-4b82-b91d-d83410b015ec', '24d2b05c-fad9-4377-9c45-63fd406790e2', '95311371-2408-46d8-8284-bc197fc1f192', 'b77386e5-8e6b-4a9a-80bf-72ccb8d4c5be', '5d414863-8750-4527-8757-7f9901911c1d', '6de00e45-8fc2-4170-a95d-322857168fb8', '55a58ad9-98c5-4666-97f3-2708320d280d', '35a2a7ff-1450-4fda-933b-e233ae0866de', 'f88e6c12-63fe-455c-ac60-c57017e3fe5c', '5ca9cab8-37de-44dc-8b2a-611d03331634']